### ISSUE TITLE
Compatibility with Eloquent strictness / fillable

### ISSUE THREAD

**Issue by onlime** [kolossal-io/laravel-multiplex#19]
Since Laravel 9.x/10.x, it's recommended to enable [Eloquent Strictness](https://laravel.com/docs/10.x/eloquent#configuring-eloquent-strictness) in your `AppServiceProvider` in non-production environment, using `Model::shouldBeStrict()` or at least `Model::preventAccessingMissingAttributes()`. But laravel-multiplex does not seem to play nicely with it, **if we add a meta data key to the `$fillable` array of a model**.

I am getting a `Illuminate \ Database \ Eloquent \ MissingAttributeException` exception when trying to access a meta data key that is `null` (not set on the model), but present in explicitly defined `$metaKeys`.
This exception gets thrown on [HasMeta.php#L449](https://github.com/kolossal-io/laravel-multiplex/blob/main/src/HasMeta.php#L449), when delegating back to `parent::getAttribute()`:

```php
         * Finally delegate back to `parent::getAttribute()` if no meta exists.
         */
        return $value ?? value(
            fn () => !$this->hasMeta($key) ? parent::getAttribute($key) : null
        );
```

Is there a way to add meta data keys to `$fillable` but still having `preventAccessingMissingAttributes` enabled? Or is there another way in laravel-multiplex of making meta data keys available in fillable?

**Comment by onlime** [comment]
nice! I have just figured it out how to use the metadata key in `$fillable`, simply by moving it from `$metaKeys` to a `MetaAttribute` cast:

```php
    protected $fillable = [
        // ...
        'my_meta_key',
    ];

    protected $casts = [
        // ...
        'my_meta_key' => MetaAttribute::class,
    ];

    // protected $metaKeys = [
    //     'my_meta_key',
    // ];
```

If this is the recommended way, please close this issue, or maybe add an extra section about `fillable` usage to the README. If not, consider this as feature request. Thanks!

**Comment by marijoo** [comment]
@onlime Good question. My first approach would be that if you would want to be strict, you’d rather use get `getMeta()` and `setMeta()` methods. What do you think?

Btw: I didn’t find anything about a recommendation for using strictness in the cited docs.

**Comment by onlime** [comment]
> My first approach would be that if you would want to be strict, you’d rather use get `getMeta()` and `setMeta()` methods. What do you think?

Yes, that would work. But as said I would like to add the key to the `$fillable` array, so I can easily create a model in my controller by assigning all `$request->validate()` data. The above workaround (explicitly adding the meta keys as `MetaAttribute` casts) works perfectly. I was only confused there's no hint about this in the docs.

If you look at `Illuminate\Database\Eloquent\Concerns\HasAttributes::getAttribute()` [HasAttributes.php#L441](https://github.com/laravel/framework/blob/v10.13.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L441), we're on the safe side, as we don't end up in `$this->throwMissingAttributeExceptionIfApplicable($key)` as long as the key `isClassCastable`.

**Comment by marijoo** [comment]
Okay, I understand. I will keep this open and add a note about this to the docs as soon as I find the time. Or feel free to open a PR for that. :) Thanks for the clarification!

**Comment by marijoo** [comment]
https://twitter.com/taylorotwell/status/1667910732749389826?s=46&t=eNK5BKcqNGrxLtLQGdqKWQ ;)

**Comment by onlime** [comment]
> https://twitter.com/taylorotwell/status/1667910732749389826?s=46&t=eNK5BKcqNGrxLtLQGdqKWQ ;)

sure I read that! and I was shocked. halfway, honestly.
