### ISSUE TITLE
where save meta details??

### ISSUE THREAD

**Issue by nekooee** [kolossal-io/laravel-multiplex#2]
I did not find in the document where this meta information is stored.
Also, I did not understand exactly what it means when you set the time for example +2 years. And what does this do?
Is it possible to explain more about the functionality of this package? I think a metadata table related to other tables does the same thing. So what is the need for this package?

**Comment by marijoo** [comment]
@nekooee Thanks for the feedback which is very welcome. I’m planning to write up a more clear intro for the README with an explicit use case. The next week looks promising.

**Comment by marijoo** [comment]
@nekooee I’ve just updated the readme on [why there is another package](https://github.com/kolossal-io/laravel-multiplex#why-another-metadata-package) and extracted the section about [how data is stored](https://github.com/kolossal-io/laravel-multiplex#how-metadata-is-stored) hope that this clears things up a bit for you.
