### ISSUE TITLE
Ulid Data truncated for column 'metable_id' 

### ISSUE THREAD

**Issue by Grazulex** [kolossal-io/laravel-multiplex#26]
Hello,

The primary key of my model is a ulid type and when a try to insert metas I have this error :

`" SQLSTATE[01000]: Warning: 1265 Data truncated for column 'metable_id' at row 1 (Connection: mysql, SQL: insert into `meta` (`key`, `type`, `value`, `published_at`, `metable_id`, `metable_type`, `updated_at`, `created_at`) values (color, integer, 87, 2023-12-17 07:12:59, 01hhv9xdt2nbx12zgffb76vpy8, App\Models\Item, 2023-12-17 07:12:59, 2023-12-17 07:12:59))"`

Can I change something to use ulid and not id ?

Thanks you

**Comment by Grazulex** [comment]
temporaly, I have change your migration file to

$table->ulidMorphs('metable');

**Comment by marijoo** [comment]
Will have a look at this, thanks.

**Comment by marijoo** [comment]
I think what you did (changing the migration file) is the way to go. Or do you have another recommendation? 

Just checked how this problem is handled in another package: https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid

**Comment by Grazulex** [comment]
The best would have been to have the choice of morph type during installation but I don't know how to do that.
I propose to make a merge request to update Readme file to indicate the procedure to follow to create a local migration file for the use of UUID, ULID,...

**Comment by Grazulex** [comment]
see https://github.com/kolossal-io/laravel-multiplex/pull/27

**Comment by marijoo** [comment]
I’m thinking about having this configurable. So one would have to publish the config before migration, choose between numeric ids or UUID/ULID and then the migration would take this into account. What do you think?

**Comment by Grazulex** [comment]
idd...that will be beter...in the config file have a option to choice beteween ids (default) or uuid or ulid and when you run the migration, choice the good morph type link to the config.

Do you want that I try to do it ?

**Comment by marijoo** [comment]
Would happily accept a PR for that, yes. But please add test cases for having `uuid` or `ulid` enabled. :)

Otherwise I may will find the time towards the end of the week.
