### ISSUE TITLE
Relation null try to find meta

### ISSUE THREAD

**Issue by vinnygambiny** [kolossal-io/laravel-multiplex#8]
I have an issue when the model have a relation loaded but `null`, the `getAttribute` from `HasMeta` try to find the meta.

I think you should add the `isRelation` for the `isModelAttribute`. You should probably use the `hasAttributeMutator` too.

**Comment by marijoo** [comment]
Thank you, I will have a look in the next week or two. Or would you be willing to open a PR and add a test case?

**Comment by marijoo** [comment]
Fixed by https://github.com/kolossal-io/laravel-multiplex/commit/e51690ade5405fd1c8976e6872e839f32f3c5f12
